export type CropCategory = "vegetable" | "fruit" | "grain_spice";

export interface CropItem {
  id: string;
  category: CropCategory;
  en: string;
  ta: string;
  te: string;
  ml: string;
  hi?: string;
  kn?: string;
  mr?: string;
  bn?: string;
  gu?: string;
  pa?: string;
  or?: string;
  [key: string]: unknown;
}

export const ALL_CROPS: CropItem[] = [
  // --- VEGETABLES ---
  {
    id: "tomato",
    hi: "टमाटर",
    kn: "ಟೊಮೆಟೊ",
    mr: "टोमॅटो",
    bn: "টমেটো",
    gu: "ટામેટા",
    pa: "ਟਮਾਟਰ",
    category: "vegetable",
    en: "Tomato (Hybrid/Desi)",
    ta: "தக்காளி",
    te: "టమాటా",
    ml: "തക്കാളി",
  },
  {
    id: "onion",
    hi: "प्याज़",
    kn: "ಈರುಳ್ಳಿ",
    mr: "कांदा",
    bn: "পেঁয়াজ",
    gu: "ડુંગળી",
    pa: "ਪਿਆਜ਼",
    category: "vegetable",
    en: "Onion (Red/Bellary)",
    ta: "வெங்காயம்",
    te: "ఉల్లి",
    ml: "സവാള",
  },
  {
    id: "potato",
    hi: "आलू",
    kn: "ಆಲೂಗಡ್ಡೆ",
    mr: "बटाटा",
    bn: "আলু",
    gu: "બટાકા",
    pa: "ਆਲੂ",
    category: "vegetable",
    en: "Potato (Jyoti/Agra)",
    ta: "உருளைக்கிழங்கு",
    te: "బంగాళాదుంప",
    ml: "ഉരുളക്കിഴങ്ങ്",
  },
  {
    id: "chilli",
    hi: "हरी मिर्च",
    kn: "ಹಸಿರು ಮೆಣಸಿನಕಾಯಿ",
    mr: "हिरवी मिरची",
    bn: "কাঁচা মরিচ",
    gu: "લીલા મરચા",
    pa: "ਹਰੀ ਮਿਰਚ",
    category: "vegetable",
    en: "Green Chilli (G4)",
    ta: "பச்சை மிளகாய்",
    te: "పచ్చిమిర్చి",
    ml: "പച്ചമുളക്",
  },
  {
    id: "brinjal",
    hi: "बैंगन",
    kn: "ಬದನೆಕಾಯಿ",
    mr: "वांगी",
    bn: "বেগুন",
    gu: "રીંગણ",
    pa: "ਬੈਂਗਣ",
    category: "vegetable",
    en: "Brinjal / Eggplant",
    ta: "கத்தரிக்காய்",
    te: "వంకాయ",
    ml: "വഴുതനങ്ങ",
  },
  {
    id: "okra",
    hi: "भिंडी",
    kn: "ಬೆಂಡೆಕಾಯಿ",
    mr: "भेंडी",
    bn: "ঢ্যাঁড়শ",
    gu: "ભીંડા",
    pa: "ਭਿੰਡੀ",
    category: "vegetable",
    en: "Ladies Finger / Okra",
    ta: "வெண்டைக்காய்",
    te: "బెండకాయ",
    ml: "വെണ്ടയ്ക്ക",
  },
  {
    id: "cabbage",
    hi: "पत्ता गोभी",
    kn: "ಎಲೆಕೋಸು",
    mr: "कोबी",
    bn: "বাঁধাকপি",
    gu: "કોબી",
    pa: "ਬੰਦ ਗੋਭੀ",
    category: "vegetable",
    en: "Cabbage",
    ta: "முட்டைக்கோஸ்",
    te: "క్యాబేజీ",
    ml: "കാബേജ്",
  },
  {
    id: "cauliflower",
    hi: "फूलगोभी",
    kn: "ಹೂಕೋಸು",
    mr: "फ्लॉवर",
    bn: "ফুলকপি",
    gu: "ફૂલેવર",
    pa: "ਫੁੱਲ ਗੋਭੀ",
    category: "vegetable",
    en: "Cauliflower",
    ta: "காலிஃபிளவர்",
    te: "క్యాలీఫ్లవర్",
    ml: "കോളിഫ്ലവർ",
  },
  {
    id: "carrot",
    hi: "गाजर",
    kn: "ಕ್ಯಾರೆಟ್",
    mr: "गाजर",
    bn: "গাজর",
    gu: "ગાજર",
    pa: "ਗਾਜਰ",
    category: "vegetable",
    en: "Carrot (Ooty/Orange)",
    ta: "கேரட்",
    te: "క్యారెట్",
    ml: "കാരറ്റ്",
  },
  {
    id: "garlic",
    hi: "लहसुन",
    kn: "ಬೆಳ್ಳುಳ್ಳಿ",
    mr: "लसूण",
    bn: "রসুন",
    gu: "લસણ",
    pa: "ਲਸਣ",
    category: "vegetable",
    en: "Garlic (Mandsaur)",
    ta: "பூண்டு",
    te: "వెల్లుల్లి",
    ml: "വെളുത്തുള്ളി",
  },
  {
    id: "ginger",
    hi: "अदरक",
    kn: "ಶುಂಠಿ",
    mr: "आले",
    bn: "আদা",
    gu: "આદુ",
    pa: "ਅਦਰਕ",
    category: "vegetable",
    en: "Ginger (Fresh green)",
    ta: "இஞ்சி",
    te: "అల్లం",
    ml: "ഇഞ്ചി",
  },
  {
    id: "bottle_gourd",
    hi: "लौकी",
    kn: "ಸೋರೆಕಾಯಿ",
    mr: "दुधी भोपळा",
    bn: "লাউ",
    gu: "દૂધી",
    pa: "ਘੀਆ",
    category: "vegetable",
    en: "Bottle Gourd / Lauki",
    ta: "சுரைக்காய்",
    te: "సొరకాయ",
    ml: "ചുരയ്ക്ക",
  },
  {
    id: "bitter_gourd",
    hi: "करेला",
    kn: "ಹಾಗಲಕಾಯಿ",
    mr: "कारले",
    bn: "করলা",
    gu: "કારેલા",
    pa: "ਕਰੇਲਾ",
    category: "vegetable",
    en: "Bitter Gourd / Karela",
    ta: "பாகற்காய்",
    te: "కాకరకాయ",
    ml: "പാവയ്ക്ക",
  },
  {
    id: "capsicum",
    hi: "शिमला मिर्च",
    kn: "ದಪ್ಪ ಮೆಣಸಿನಕಾಯಿ",
    mr: "ढोबळी मिरची",
    bn: "ক্যাপসিকাম",
    gu: "કેપ્સિકમ",
    pa: "ਸ਼ਿਮਲਾ ਮਿਰਚ",
    category: "vegetable",
    en: "Capsicum (Bell Pepper)",
    ta: "குடைமிளகாய்",
    te: "క్యాప్సికమ్",
    ml: "കാപ്സിക്കം",
  },
  {
    id: "drumstick",
    hi: "सहजन / मोरिंगा",
    kn: "ನುಗ್ಗೆಕಾಯಿ",
    mr: "शेवगा",
    bn: "সজনে ডাঁটা",
    gu: "સરગવો",
    pa: "ਸੁਹਾਂਜਣਾ",
    category: "vegetable",
    en: "Drumstick / Moringa",
    ta: "முருங்கைக்காய்",
    te: "ములక్కాడ",
    ml: "മുരിങ്ങയ്ക്ക",
  },
  {
    id: "beetroot",
    hi: "चुकंदर",
    kn: "ಬೀಟ್ರೂಟ್",
    mr: "बीट",
    bn: "বিট",
    gu: "બીટ",
    pa: "ਚੁਕੰਦਰ",
    category: "vegetable",
    en: "Beetroot",
    ta: "பீட்ரூட்",
    te: "బీట్‌రూట్",
    ml: "ബീറ്റ്‌റൂട്ട്",
  },
  {
    id: "cucumber",
    hi: "खीरा",
    kn: "ಸೌತೆಕಾಯಿ",
    mr: "काकडी",
    bn: "শসা",
    gu: "કાકડી",
    pa: "ਖੀਰਾ",
    category: "vegetable",
    en: "Cucumber",
    ta: "வெள்ளரிக்காய்",
    te: "దోసకాయ",
    ml: "വെള്ളരിക്ക",
  },

  // --- FRUITS ---
  {
    id: "banana",
    hi: "केला",
    kn: "ಬಾಳೆಹಣ್ಣು",
    mr: "केळी",
    bn: "কলা",
    gu: "કેળા",
    pa: "ਕੇਲਾ",
    category: "fruit",
    en: "Banana (Robusta/Yelakki)",
    ta: "வாழைப்பழம்",
    te: "అరటిపండు",
    ml: "വാഴപ്പഴം",
  },
  {
    id: "mango",
    hi: "आम",
    kn: "ಮಾವಿನಹಣ್ಣು",
    mr: "आंबा",
    bn: "আম",
    gu: "કેરી",
    pa: "ਅੰਬ",
    category: "fruit",
    en: "Mango (Alphonso/Banganapalli)",
    ta: "மாம்பழம்",
    te: "మామిడి",
    ml: "മാമ്പഴം",
  },
  {
    id: "apple",
    hi: "सेब",
    kn: "ಸೇಬು",
    mr: "सफरचंद",
    bn: "আপেল",
    gu: "સફરજન",
    pa: "ਸੇਬ",
    category: "fruit",
    en: "Apple (Kashmir/Shimla)",
    ta: "ஆப்பிள்",
    te: "ఆపిల్",
    ml: "ആപ്പിൾ",
  },
  {
    id: "pomegranate",
    hi: "अनार",
    kn: "ದಾಳಿಂಬೆ",
    mr: "डाळಿಂಬ",
    bn: "ডালিম",
    gu: "દાડમ",
    pa: "ਅਨਾਰ",
    category: "fruit",
    en: "Pomegranate (Bhagwa)",
    ta: "மாதுளை",
    te: "దానిమ్మ",
    ml: "മാതളനാരങ്ങ",
  },
  {
    id: "papaya",
    hi: "पपीता",
    kn: "ಪರಂಗಿ / ಪಪ್ಪಾಯಿ",
    mr: "पपई",
    bn: "পেঁপে",
    gu: "પપૈયું",
    pa: "ਪਪੀਤਾ",
    category: "fruit",
    en: "Papaya (Red Lady)",
    ta: "பப்பாளி",
    te: "బొప్పాయి",
    ml: "പപ്പായ",
  },
  {
    id: "orange",
    hi: "संतरा",
    kn: "ಕಿತ್ತಳೆ",
    mr: "संत्रे",
    bn: "কমলালেবু",
    gu: "સંતરા",
    pa: "ਸੰਤਰਾ",
    category: "fruit",
    en: "Orange (Nagpur)",
    ta: "ஆரஞ்சு",
    te: "నారింజ",
    ml: "ഓറഞ്ച്",
  },
  {
    id: "grapes",
    hi: "अंगूर",
    kn: "ದ್ರಾಕ್ಷಿ",
    mr: "द्राक्षे",
    bn: "আঙুর",
    gu: "દ્રાક્ષ",
    pa: "ਅੰਗੂਰ",
    category: "fruit",
    en: "Grapes (Thompson Seedless)",
    ta: "திராட்சை",
    te: "ద్రాక్ష",
    ml: "മുന്തിരി",
  },
  {
    id: "watermelon",
    hi: "तरबूज",
    kn: "ಕಲ್ಲಂಗಡಿ",
    mr: "कलिंगड",
    bn: "তরমুজ",
    gu: "તરબૂચ",
    pa: "ਤਰਬੂਜ਼",
    category: "fruit",
    en: "Watermelon",
    ta: "தர்பூசணி",
    te: "పుచ్చకాయ",
    ml: "തണ്ണീർമത്തൻ",
  },
  {
    id: "guava",
    hi: "अमरूद",
    kn: "ಸೀಬೆಹಣ್ಣು",
    mr: "पेरू",
    bn: "পেয়ারা",
    gu: "જામફળ",
    pa: "ਅਮਰੂਦ",
    category: "fruit",
    en: "Guava (Safeda)",
    ta: "கொய்யா",
    te: "జామకాయ",
    ml: "പേരയ്ക്ക",
  },
  {
    id: "pineapple",
    hi: "अनानास",
    kn: "ಅನಾನಸ್",
    mr: "अननस",
    bn: "আনারস",
    gu: "અનાનસ",
    pa: "ਅਨਾਨਾਸ",
    category: "fruit",
    en: "Pineapple (Queen)",
    ta: "அன்னாசி",
    te: "అనాసపండు",
    ml: "കൈതച്ചക്ക",
  },
  {
    id: "sapota",
    hi: "चीकू",
    kn: "ಸಪೋಟ / ಚಿಕ್ಕು",
    mr: "चिकू",
    bn: "সফেদা",
    gu: "ચીકુ",
    pa: "ਚੀਕੂ",
    category: "fruit",
    en: "Sapota / Chiku",
    ta: "சப்போட்டா",
    te: "సపోటా",
    ml: "സപ്പോട്ട",
  },
  {
    id: "sweet_lime",
    hi: "मौसंबी",
    kn: "ಮೋಸಂಬಿ",
    mr: "मोसंबी",
    bn: "মৌসাম্বি",
    gu: "મોસંબી",
    pa: "ਮੁਸੰਮੀ",
    category: "fruit",
    en: "Sweet Lime / Mosambi",
    ta: "சாத்துக்குடி",
    te: "బత్తాయి",
    ml: "മൊസമ്പി",
  },
  {
    id: "lemon",
    hi: "नींबू",
    kn: "ನಿಂಬೆಹಣ್ಣು",
    mr: "लिंबू",
    bn: "লেবু",
    gu: "લીંબુ",
    pa: "ਨਿੰਬੂ",
    category: "fruit",
    en: "Lemon (Kagzi)",
    ta: "எலுமிச்சை",
    te: "నిమ్మకాయ",
    ml: "ചെറുനാരങ്ങ",
  },

  // --- GRAINS, SPICES & CASH CROPS ---
  {
    id: "rice",
    hi: "धान / चावल",
    kn: "ಭತ್ತ / ಅಕ್ಕಿ",
    mr: "भात / तांदूळ",
    bn: "ধান / চাল",
    gu: "ડાંગર / ચોખા",
    pa: "ਝੋਨਾ / ਚੌਲ",
    category: "grain_spice",
    en: "Rice, Sona Masuri",
    ta: "அரிசி",
    te: "బియ్యం",
    ml: "അരി",
  },
  {
    id: "turmeric",
    hi: "हल्दी",
    kn: "ಅರಿಶಿನ",
    mr: "हळद",
    bn: "হলুদ",
    gu: "હળદર",
    pa: "ਹਲਦੀ",
    category: "grain_spice",
    en: "Turmeric (Salem/Nizamabad)",
    ta: "மஞ்சள்",
    te: "పసుపు",
    ml: "മഞ്ഞൾ",
  },
  {
    id: "coconut",
    hi: "नारियल",
    kn: "ತೆಂಗಿನಕಾಯಿ",
    mr: "नारळ",
    bn: "নারকেল",
    gu: "નાળિયેર",
    pa: "ਨਾਰੀਅਲ",
    category: "grain_spice",
    en: "Coconut (Pollachi)",
    ta: "தேங்காய்",
    te: "కొబ్బరి",
    ml: "തേങ്ങ",
  },
  {
    id: "groundnut",
    hi: "मूंगफली",
    kn: "ಕಡಲೆಕಾಯಿ",
    mr: "भुईमूग",
    bn: "চীনাবাদাম",
    gu: "મગફળી",
    pa: "ਮੂੰਗਫਲੀ",
    category: "grain_spice",
    en: "Groundnut (Pod)",
    ta: "நிலக்கடலை",
    te: "వేరుశనగ",
    ml: "നിലക്കടല",
  },
  {
    id: "pepper",
    hi: "काली मिर्च",
    kn: "ಕಾಳು ಮೆಣಸು",
    mr: "काळी मिरी",
    bn: "গোলমরিচ",
    gu: "કાળા મરી",
    pa: "ਕਾਲੀ ਮਿਰਚ",
    category: "grain_spice",
    en: "Black pepper (Malabar)",
    ta: "மிளகு",
    te: "మిరియాలు",
    ml: "കുരുമുളക്",
  },
  {
    id: "dry_chilli",
    hi: "सूखी लाल मिर्च",
    kn: "ಒಣ ಮೆಣಸಿನಕಾಯಿ",
    mr: "सुकलेली मिरची",
    bn: "শুকনো লঙ্কা",
    gu: "સૂકા મરચા",
    pa: "ਸੁੱਕੀ ਲਾਲ ਮਿਰਚ",
    category: "grain_spice",
    en: "Dry Red Chilli (Guntur)",
    ta: "காய்ந்த மிளகாய்",
    te: "ఎండుమిర్చి",
    ml: "വറ്റൽമുളക്",
  },
  {
    id: "cotton",
    hi: "कपास / रुई",
    kn: "ಹತ್ತಿ",
    mr: "कापूस",
    bn: "তুলা",
    gu: "કપાસ",
    pa: "ਨਰਮਾ / ਕਪਾਹ",
    category: "grain_spice",
    en: "Cotton (Medium Staple)",
    ta: "பருத்தி",
    te: "పత్తి",
    ml: "പരുത്തി",
  },
  {
    id: "wheat",
    hi: "गेहूं",
    kn: "ಗೋಧಿ",
    mr: "गहू",
    bn: "গম",
    gu: "ઘઉં",
    pa: "ਕਣਕ",
    category: "grain_spice",
    en: "Wheat (Sharbati/Lokwan)",
    ta: "கோதுமை",
    te: "గోధుమలు",
    ml: "ഗോതമ്പ്",
  },
  {
    id: "maize",
    hi: "मक्का",
    kn: "ಮೆಕ್ಕೆಜೋಳ",
    mr: "मका",
    bn: "ভুট্টা",
    gu: "મકાઈ",
    pa: "ਮੱਕੀ",
    category: "grain_spice",
    en: "Maize / Corn (Yellow)",
    ta: "மக்காச்சோளம்",
    te: "మొక్కజొన్న",
    ml: "ചോളം",
  },
];
